Fix sequence widgets
Pylons/deform pull request #518
Opened 2021-05-22 19:34 UTC by krysros

# Example

## Before
![before](https://user-images.githubusercontent.com/5299999/119238777-f7883080-bb44-11eb-9a45-afc02c26752a.png)

## After
![after](https://user-images.githubusercontent.com/5299999/119238781-02db5c00-bb45-11eb-8c46-dddafa66a914.png)

2021-05-22 19:55 UTC, stevepiercy commented
@krysros thank you for your contribution! 

It will be a while until I can review this.

Meanwhile deformdemo needs to be updated so the functional tests pass. Please let me know if you need help to get that running locally. We have pretty good docs to help you get started in https://github.com/Pylons/deform/blob/main/contributing.md

This also needs a note in CHANGES.txt.

Side note, `main` needs a lot more work to comply with Bootstrap 4.x before this can go in. I might also skip 4 and go straight to 5.

2021-05-22 20:11 UTC, krysros commented
I work on Windows, so running functional tests will not be an easy task. Maybe I'll try it on a virtual machine.

For now I'm pretty sure that to fix this conflict it is enough to change "panel-heading" class to "card-header" in this line:

https://github.com/Pylons/deformdemo/blob/f124a2bc846c9b66510255065f2e07fb7a87a676/deformdemo/test.py#L3374

2022-06-15 02:12 UTC, stevepiercy requested changes

2022-06-15 02:12 UTC, stevepiercy commented on deform/templates/sequence_item.pt
> +       i18n:attributes="title">&udarr;</a>
This is closer to the original.

```suggestion
       i18n:attributes="title">&updownarrow;</a>
```

Also changing from a `span` to `a` might cause some issues—with its display, usability, or accessibility—maybe not. I have not verified.

2022-06-19 08:05 UTC, krysros commented
This is what it looks like after the changes. We can go back to the [icons](https://icons.getbootstrap.com/) in Bootstrap 5.
![Zrzut ekranu z 2022-06-19 09-58-08](https://user-images.githubusercontent.com/5299999/174471670-99783f98-eb3a-4ffd-86d8-7065715c0131.png)

2025-09-18 20:52 UTC, delijati commented
fixed with BS5 merge

2025-09-18 20:52 UTC, closed without merging