[WIP] bootstrap5 + icons
Pylons/deform pull request #529
Opened 2023-11-08 13:12 UTC by delijati

Changes to work with bootstrap5 and bootstrap icons.

2023-11-08 13:44 UTC, stevepiercy commented
When released, deform (and deformdemo) should support the currently supported versions of Python, which include 3.8-3.12, as well as the most recent PyPy that is available for testing in GitHub Actions.

- https://devguide.python.org/versions/
- https://www.pypy.org/download.html

2023-11-08 17:29 UTC, trollfot commented
Should you need any help in getting this done, you can ping me.

2023-11-09 15:09 UTC, delijati commented
Got also the function tests working over here https://github.com/Pylons/deformdemo/pull/124 ...

2023-11-09 18:36 UTC, delijati commented
Here a preview (will turn if at some point) http://168.119.117.235:8523/

2023-11-13 08:13 UTC, goschtl commented
@delijati @stevepiercy Any chance to cut a release with this changes? Is there anything i can help with?

cheers Christian

2023-11-13 19:26 UTC, delijati commented
> @delijati @stevepiercy Any chance to cut a release with this changes? Is there anything i can help with?
> 
> cheers Christian

It would be nice if someone has the time and can go through the bs4 roadmap list and cross off what we already have  https://github.com/Pylons/deform/issues?q=is%3Aissue+is%3Aopen+label%3ABS4

2023-11-13 22:12 UTC, stevepiercy requested changes
One minor housekeeping change.

2023-11-13 22:12 UTC, stevepiercy commented on setup.py
Trove classifiers should include up to Python 3.12.

2023-11-13 22:17 UTC, stevepiercy commented
@delijati @goschtl for a release, I would do an alpha to start. That will allow us to get it out there for developer testing and cross off some of the issues tagged with `bs4` with greater ease in subsequent alphas. I also set a [milestone for 3.0](https://github.com/Pylons/deform/milestone/3) that needs some gardening.

Once I make an alpha release of deformdemo, we can adjust this PR to use that for the functional test suite.

2023-11-13 22:39 UTC, stevepiercy commented
@delijati would you please do two housekeeping tasks before I merge?

- Sign https://github.com/Pylons/deformd/blob/main/CONTRIBUTORS.txt
- Update docs and readme with supported Python versions (3.8, 3.9, 3.10, 3.11, and 3.12).

Thank you!

2023-11-14 09:29 UTC, delijati commented
@stevepiercy 

>     * Sign https://github.com/Pylons/deformd/blob/main/CONTRIBUTORS.txt

I'm already in CONTRIBUTERS.txt (Josip Delić)
 
>     * Update docs and readme with supported Python versions (3.8, 3.9, 3.10, 3.11, and 3.12).

The only place i found was  in `index.rst`. In the `README.rst` the versions are set by this link [1] and generated by the Trove classifiers in `setup.py`

[1] https://img.shields.io/pypi/pyversions/deform

2023-11-14 11:04 UTC, stevepiercy requested changes
I did a more thorough review on this pass.

I think we can move stuff from `deform/compat.py` into core, now that we use Python 3 exclusively, and remove it.

2023-11-14 11:04 UTC, stevepiercy commented on .github/workflows/ci-tests.yml
>        uses: actions/setup-python@v2
```suggestion
      uses: actions/setup-python@v4
```

2023-11-14 13:22 UTC, stevepiercy approved these changes
Thank you!

2023-11-14 13:53 UTC, stevepiercy commented
Functional tests fail due to a recent change in Selenium 4.10.

https://github.com/Pylons/deform/actions/runs/6864014788/job/18665635754#step:7:457

`TypeError: WebDriver.__init__() got an unexpected keyword argument 'desired_capabilities'`

https://github.com/Pylons/deform/blob/f4da7dffb0b9235babe4e99596eefd1a6170c640/setup.py#L75-L78

This should do the trick.

```python
functional_testing_extras.extend(["selenium >= 4.0.0.b4, <4.10.0"])
```

In a later alpha, we can bump Selenium and update functional tests.

2023-11-14 13:56 UTC, goschtl commented
@stevepiercy is there a roadmap or release-plan 

where/how can we help to kick out a new release?

Christian

2023-11-14 14:11 UTC, stevepiercy commented
> @stevepiercy is there a roadmap or release-plan

https://github.com/Pylons/deform/pull/529#issuecomment-1809224947
 
> where/how can we help to kick out a new release?

Get CI to pass. https://github.com/Pylons/deform/pull/529#issuecomment-1810246259

2023-11-14 20:06 UTC, delijati commented
I opened a pull request to fix the last functional test https://github.com/Pylons/deformdemo/pull/125/files

2023-11-14 21:31 UTC, stevepiercy commented
Now the tests run, but we have one test failure:

https://github.com/Pylons/deform/actions/runs/6868633228/job/18679624126?pr=529#step:7:403

I restarted the test run to see if that is a flaky test.

We also have a couple of deprecation warnings. A couple of them are in deform, with the rest in other packages. We could add the deform items to a future alpha release, and the others as issues in their repositories. I'll circle back on this PR and create issues as needed.

https://github.com/Pylons/deform/actions/runs/6868633228/job/18679624126?pr=529#step:7:405

2023-11-14 22:01 UTC, stevepiercy commented
@delijati this test still fails.

https://github.com/Pylons/deform/actions/runs/6868633228/job/18683098188#step:7:350

Strange that it works in deformdemo, but not deform... :thinking:

2023-11-14 22:02 UTC, stevepiercy approved these changes
Looks good. We need that one test in CI to pass.

2023-11-15 08:23 UTC, delijati commented
Another PR in deformdemo https://github.com/Pylons/deformdemo/pull/126

2023-11-15 08:42 UTC, stevepiercy commented
Merged the deformdemo PR, restarted CI, let's see what happens. 🤞

2023-11-15 08:50 UTC, stevepiercy commented
Same test still fails: https://github.com/Pylons/deform/actions/runs/6868633228/job/18697409622#step:7:351

2023-11-15 09:01 UTC, delijati commented
|-( i hate selenium tests ... looking into it

2023-11-15 09:38 UTC, delijati commented
@stevepiercy  ok got it working locally https://github.com/Pylons/deformdemo/pull/127/files

2023-11-15 10:49 UTC, stevepiercy commented
Restarted failed CI. 🤞

2023-11-15 11:02 UTC, delijati commented
I will add this [1] to the tests if possible ... firefox does not scroll |-( 

[1] https://stackoverflow.com/a/52045231/1154966

2023-11-15 14:19 UTC, delijati commented
Added manual scroll to be in viewport of the button https://github.com/Pylons/deformdemo/pull/128

2023-11-15 19:00 UTC, stevepiercy commented
Success! I'll merge now, and cut a 3.0.0a release later this week. Thank you for your work on this!

2023-11-15 19:00 UTC, merged